<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="37" started-at="2022-09-07T16:54:30Z" finished-at="2022-09-07T16:54:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="37" started-at="2022-09-07T16:54:30Z" finished-at="2022-09-07T16:54:30Z">
      <class name="org.com.New">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:org.com.New@5622fdf]" name="beforeClass" is-config="true" duration-ms="6" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeEachMethod()[pri:0, instance:org.com.New@5622fdf]" name="beforeEachMethod" is-config="true" duration-ms="0" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeEachMethod -->
        <test-method status="PASS" signature="tc1()[pri:0, instance:org.com.New@5622fdf]" name="tc1" duration-ms="6" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="afterEachMethod()[pri:0, instance:org.com.New@5622fdf]" name="afterEachMethod" is-config="true" duration-ms="1" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachMethod -->
        <test-method status="FAIL" signature="tc12()[pri:0, instance:org.com.New@5622fdf]" name="tc12" duration-ms="4" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [JAVA2] but found [JAVA]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [JAVA2] but found [JAVA]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at org.com.New.tc12(New.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc12 -->
        <test-method status="PASS" signature="beforeEachMethod()[pri:0, instance:org.com.New@5622fdf]" name="beforeEachMethod" is-config="true" duration-ms="0" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeEachMethod -->
        <test-method status="PASS" signature="afterEachMethod()[pri:0, instance:org.com.New@5622fdf]" name="afterEachMethod" is-config="true" duration-ms="1" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:org.com.New@5622fdf]" name="afterClass" is-config="true" duration-ms="1" started-at="2022-09-07T22:24:30Z" finished-at="2022-09-07T22:24:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- org.com.New -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
